projects:
  BoyakiGql:
    schemaPath: amplify/backend/api/BoyakiGql/build/schema.graphql
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        region: us-east-1
        apiId: null
        maxDepth: 3
extensions:
  amplify:
    version: 3
